# Site settings
title: "Soumya Chopra"
email: soumyachopra@gmail.com
description: "Blog"
#baseurl: "https://soumyachopra.github.io"
url: "soumyachopra.githb.io"
title_description: "A blog by me"
title_image: "/favicons/pic.jpg"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
#github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
github_username: Soumya0803
twitter_username: Soumya27331438
#instagram_username: 
#reddit_username: 
linkedin_link: https://www.linkedin.com/in/soumya-chopra-8b822a146/
#google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
#stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
#xing_link:
facebook_link: https://www.facebook.com/soumya.chopraa

# Footer
#footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
